DROP TABLE IF EXISTS USER_CONTACT;
DROP TABLE IF EXISTS USER_SETTING;
DROP TABLE IF EXISTS USER_TAB;
DROP TABLE IF EXISTS BUSINESSCONTACT;
DROP TABLE IF EXISTS BUSINESSADDRESS;
DROP TABLE IF EXISTS USERCREDITCARD;
DROP TABLE IF EXISTS USER_ADDRESS;
DROP TABLE IF EXISTS USER_ACTIVITY;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS NOTIFICATION_LOG;
DROP TABLE IF EXISTS BUSINESS;

CREATE TABLE BUSINESS (
       BUSINESS_ID BIGINT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , USERNAME VARCHAR(50) NOT NULL
     , PASSWORD VARCHAR(20) NOT NULL
     , SIGNUP_DATE TIMESTAMP NOT NULL
     , ACTIVE BOOLEAN NOT NULL
     , DEACTIVE_DATE TIMESTAMP
     , ACCOUNT_NUMBER VARCHAR(10) NOT NULL
     , PRIMARY KEY (BUSINESS_ID)
);

CREATE TABLE NOTIFICATION_LOG (
       NOTIFICATION_LOG_ID BIGINT NOT NULL AUTO_INCREMENT
     , TYPE INTEGER NOT NULL
     , NUMBER VARCHAR(20) NOT NULL
     , NOTIFICATION VARCHAR(200) NOT NULL
     , NOTIFICATION_BY INTEGER NOT NULL
     , NOTIFICATION_TIME TIMESTAMP NOT NULL
     , PRIMARY KEY (NOTIFICATION_LOG_ID)
);

CREATE TABLE USER (
       USER_ID BIGINT NOT NULL AUTO_INCREMENT
     , USERNAME VARCHAR(100) NOT NULL
     , FIRSTNAME VARCHAR(50) NOT NULL
     , LASTNAME VARCHAR(50) NOT NULL
     , EMAIL VARCHAR(100) NOT NULL
     , PASSWORD VARCHAR(50) NOT NULL
     , PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_ACTIVITY (
       USER_ACTIVITY_ID BIGINT NOT NULL AUTO_INCREMENT
     , CHECKIN_TIME TIMESTAMP NOT NULL
     , CHECKOUT_TIME TIMESTAMP
     , USER_ID BIGINT NOT NULL
     , BUSINESS_ID BIGINT NOT NULL
     , CHECKOUT_BY INTEGER
     , PRIMARY KEY (USER_ACTIVITY_ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USER_ACTIVITY_1 FOREIGN KEY (USER_ID)
                  REFERENCES USER (USER_ID)
     , INDEX (BUSINESS_ID)
     , CONSTRAINT FK_USER_ACTIVITY_2 FOREIGN KEY (BUSINESS_ID)
                  REFERENCES BUSINESS (BUSINESS_ID)
);

CREATE TABLE USER_ADDRESS (
       USER_ADDRESS_ID BIGINT NOT NULL AUTO_INCREMENT
     , TYPE INTEGER NOT NULL
     , ADDRESS VARCHAR(100) NOT NULL
     , ADDRESS2 VARCHAR(50)
     , CITY VARCHAR(100) NOT NULL
     , STATE VARCHAR(10) NOT NULL
     , ZIPCODE VARCHAR(10) NOT NULL
     , USER_ID BIGINT NOT NULL
     , PRIMARY KEY (USER_ADDRESS_ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USER_ADDRESS_1 FOREIGN KEY (USER_ID)
                  REFERENCES USER (USER_ID)
);

CREATE TABLE USERCREDITCARD (
       USERCREDITCARD_ID BIGINT NOT NULL AUTO_INCREMENT
     , CARD_TYPE VARCHAR(20) NOT NULL
     , CARD_NUMBER VARCHAR(20) NOT NULL
     , CARD_HOLDER_NAME VARCHAR(100)
     , EXPIRY_MONTH_YEAR VARCHAR(10) NOT NULL
     , USER_ID BIGINT NOT NULL
     , PRIMARY KEY (USERCREDITCARD_ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USERCREDITCARD_1 FOREIGN KEY (USER_ID)
                  REFERENCES USER (USER_ID)
);

CREATE TABLE BUSINESSADDRESS (
       BUSINESSADDRESS_ID BIGINT NOT NULL AUTO_INCREMENT
     , TYPE INTEGER NOT NULL
     , ADDRESS VARCHAR(200) NOT NULL
     , ADDRESS2 BIGINT
     , CITY VARCHAR(100) NOT NULL
     , STATE VARCHAR(10) NOT NULL
     , ZIPCODE VARCHAR(10) NOT NULL
     , BUSINESS_ID BIGINT NOT NULL
     , PRIMARY KEY (BUSINESSADDRESS_ID)
     , INDEX (BUSINESS_ID)
     , CONSTRAINT FK_BUSINESSADDRESS_1 FOREIGN KEY (BUSINESS_ID)
                  REFERENCES BUSINESS (BUSINESS_ID)
);

CREATE TABLE BUSINESSCONTACT (
       BUSINESSCONTACT_ID BIGINT NOT NULL AUTO_INCREMENT
     , TYPE INTEGER NOT NULL
     , NUMBER VARCHAR(20) NOT NULL
     , BUSINESS_ID BIGINT NOT NULL
     , NAME VARCHAR(100)
     , PRIMARY KEY (BUSINESSCONTACT_ID)
     , INDEX (BUSINESS_ID)
     , CONSTRAINT FK_BUSINESSCONTACT_1 FOREIGN KEY (BUSINESS_ID)
                  REFERENCES BUSINESS (BUSINESS_ID)
);

CREATE TABLE USER_TAB (
       USER_TAB_ID BIGINT NOT NULL AUTO_INCREMENT
     , ITEM VARCHAR(50) NOT NULL
     , QUANTITY INTEGER NOT NULL
     , PURCHASE_TIME TIMESTAMP NOT NULL
     , SKUCODE VARCHAR(50)
     , DESCRIPTION VARCHAR(200)
     , USER_ACTIVITY_ID BIGINT NOT NULL
     , PRIMARY KEY (USER_TAB_ID)
     , INDEX (USER_ACTIVITY_ID)
     , CONSTRAINT FK_USER_TAB_1 FOREIGN KEY (USER_ACTIVITY_ID)
                  REFERENCES USER_ACTIVITY (USER_ACTIVITY_ID)
);

CREATE TABLE USER_SETTING (
       USER_SETTING_ID BIGINT NOT NULL AUTO_INCREMENT
     , SETTING VARCHAR(50) NOT NULL
     , VALUE INTEGER NOT NULL
     , USER_ID BIGINT NOT NULL
     , PRIMARY KEY (USER_SETTING_ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USER_SETTING_1 FOREIGN KEY (USER_ID)
                  REFERENCES USER (USER_ID)
);

CREATE TABLE USER_CONTACT (
       USER_CONTACT_ID BIGINT NOT NULL AUTO_INCREMENT
     , NUMBER VARCHAR(20) NOT NULL
     , TYPE INTEGER NOT NULL
     , USER_ID BIGINT NOT NULL
     , PRIMARY KEY (USER_CONTACT_ID, TYPE)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USER_CONTACT_1 FOREIGN KEY (USER_ID)
                  REFERENCES USER (USER_ID)
);

