package FlashPay::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'FlashPay::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:textclose',
        user => 'flashpay',
        password => 'payflash',
        AutoCommit => q{1},
    }
);

=head1 NAME

FlashPay::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FlashPay>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FlashPay::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

andrew

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
